name: Generate Report & Deploy Report
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  install_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - name: Install Depedencies
        run: npm ci
      - name: lint
        run: npm run format

  run-tests:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci
      - name: Install Allure CI
        run: npm install -g allure-commandline --save-dev

      - name: Run tests
        run: npm run ci:tests

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

  deploy:
    needs: run-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Allure Reports
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          force_orphan: false
