name: Schedule Pipeline & Deploy Report
on:
  schedule:
    - cron: 0 01 * * 1-5

permissions:
  contents: write

jobs:
  install_and_lint:
    runs-on: ubuntu-latest
    steps:
      - &node_setup
        name: Repo Checkout
        uses: actions/checkout@v3
      - &node_install
        name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - &npm_ci
        name: Install Depedencies
        run: npm ci
      - name: lint
        run: npm run format

  run-tests:
    needs: install_and_lint
    runs-on: ubuntu-latest
    steps:
      - *node_setup
      - *node_install
      - *npm_ci
      - name: Install Allure CI
        run: npm install -g allure-commandline --save-dev

      - name: Run tests
        run: npm run ci:tests

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

  deploy:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - *node_setup

      - name: Download Allure Reports
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          force_orphan: false
